# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_shopping_cart}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Padilla"]
  s.date = %q{2010-09-07}
  s.description = %q{A simple shopping cart implementation}
  s.email = %q{david.padilla@crowdint.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "acts_as_shopping_cart.gemspec",
     "lib/active_record/acts/shopping_cart.rb",
     "lib/active_record/acts/shopping_cart/cart_instance_methods.rb",
     "lib/active_record/acts/shopping_cart/cart_item_instance_methods.rb",
     "lib/active_record/acts/shopping_cart/item_instance_methods.rb",
     "lib/active_record/acts/shopping_cart_item.rb",
     "lib/acts_as_shopping_cart.rb",
     "spec/active_record/acts/shopping_cart/cart_instance_methods_spec.rb",
     "spec/active_record/acts/shopping_cart/cart_item_instance_methods_spec.rb",
     "spec/active_record/acts/shopping_cart/item_instance_methods_spec.rb",
     "spec/acts_as_shopping_cart_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/dabit/acts_as_shopping_cart}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A simple shopping cart implementation}
  s.test_files = [
    "spec/active_record/acts/shopping_cart/cart_item_instance_methods_spec.rb",
     "spec/active_record/acts/shopping_cart/cart_instance_methods_spec.rb",
     "spec/active_record/acts/shopping_cart/item_instance_methods_spec.rb",
     "spec/acts_as_shopping_cart_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

